### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.http.client.methods.HttpPost.setConfig

### ISSUE THREAD

**Issue by rshivane** [ApptuitAI/JInsight#2]
If the java application has an older version of apache httpclient ahead in the classpath, ApptuitReporter generates a NoSuchMethodError

```
2017-12-20 09:50:55,996 [metrics-apptuit-reporter-1-thread-1] ERROR [] [] [ScheduledReporter.run] - Exception thrown from ApptuitReporter#report. Exception was suppressed.
java.lang.NoSuchMethodError: org.apache.http.client.methods.HttpPost.setConfig(Lorg/apache/http/client/config/RequestConfig;)V
    at ai.apptuit.metrics.client.ApptuitPutClient.put(ApptuitPutClient.java:72) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.dropwizard.ApptuitReporter.lambda$report$9(ApptuitReporter.java:109) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.codahale.Timer.time(Timer.java:116) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.dropwizard.ApptuitReporter.report(ApptuitReporter.java:107) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.codahale.ScheduledReporter.report(ScheduledReporter.java:235) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.codahale.ScheduledReporter$1.run(ScheduledReporter.java:174) ~[jinsight-0.4.5.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

2017-12-20 09:51:01,002 [metrics-apptuit-reporter-1-thread-1] ERROR [] [] [ScheduledReporter.run] - Exception thrown from ApptuitReporter#report. Exception was suppressed.
java.lang.NoSuchMethodError: org.apache.http.client.methods.HttpPost.setConfig(Lorg/apache/http/client/config/RequestConfig;)V
    at ai.apptuit.metrics.client.ApptuitPutClient.put(ApptuitPutClient.java:72) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.dropwizard.ApptuitReporter.lambda$report$9(ApptuitReporter.java:109) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.codahale.Timer.time(Timer.java:116) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.dropwizard.ApptuitReporter.report(ApptuitReporter.java:107) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.codahale.ScheduledReporter.report(ScheduledReporter.java:235) ~[jinsight-0.4.5.jar:na]
    at ai.apptuit.metrics.codahale.ScheduledReporter$1.run(ScheduledReporter.java:174) ~[jinsight-0.4.5.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_151]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
    at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```

**Comment by rshivane** [comment]
Removed dependency on apache http client so we do not have version conflicts with version of the http-client version bundled in the application.

Issue fixed in 6ed5b1b49000b9d513f4c367d8c37619aeab4bb9
