### ISSUE TITLE
Exceptions caught by dropwizard-metrics do not show up in logs

### ISSUE THREAD

**Issue by rshivane** [ApptuitAI/JInsight#26]
dropwizard-metrics logs errors to slf4j. Since there is no binding for slf4j, in most cases (unless the application has slf4j in boot classpath), these logs are never visible. Making debugging issues hard.

The following exception never shows up in the logs. It was obtained by putting a break-point in ScheduledReporter.report

```
java.lang.NullPointerException
        at org.jboss.byteman.rule.Rule.ensureHelperClass(Rule.java:1007)
        at org.jboss.byteman.rule.Rule.typeCheck(Rule.java:568)
        at org.jboss.byteman.rule.Rule.ensureTypeCheckedCompiled(Rule.java:521)
        at org.jboss.byteman.rule.Rule.execute(Rule.java:796)
        at org.jboss.byteman.rule.Rule.execute(Rule.java:777)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at ai.apptuit.metrics.client.ApptuitPutClient.put(ApptuitPutClient.java:102)
        at ai.apptuit.metrics.dropwizard.ApptuitReporter.lambda$report$9(ApptuitReporter.java:114)
        at com.codahale.metrics.Timer.time(Timer.java:116)
        at ai.apptuit.metrics.dropwizard.ApptuitReporter.report(ApptuitReporter.java:112)
        at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:243)
        at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by rshivane** [comment]
Metrics reporting frequency is now configurable via [reporting_frequency](https://github.com/ApptuitAI/JInsight/wiki/UsageJInsightAgent#reporting_frequency) option. Defaults to 15s

Fixed in 90f0627baa1fc398b4e02838ab2ca043c602bf04
